# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo
spec:
  selector:
    matchLabels:
      app: argocd-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: myjob
    spec:
      containers:
        - name: argocd-demo
          image: nanajanashia/argocd-app:1.0
          ports:
            - containerPort: 8080
